language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# commands to install dependencies
install:
  - python setup.py -q install
# commands to run tests
script:
  - python test.py
